# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 407)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 621, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.FileTable = QtWidgets.QWidget()
        self.FileTable.setObjectName("FileTable")
        self.Edit_Path = QtWidgets.QLineEdit(self.FileTable)
        self.Edit_Path.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.Edit_Path.setInputMask("")
        self.Edit_Path.setText("")
        self.Edit_Path.setObjectName("Edit_Path")
        self.Edit_Source = QtWidgets.QLineEdit(self.FileTable)
        self.Edit_Source.setGeometry(QtCore.QRect(130, 50, 113, 20))
        self.Edit_Source.setObjectName("Edit_Source")
        self.Edit_Target = QtWidgets.QLineEdit(self.FileTable)
        self.Edit_Target.setGeometry(QtCore.QRect(130, 80, 111, 20))
        self.Edit_Target.setObjectName("Edit_Target")
        self.label = QtWidgets.QLabel(self.FileTable)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.FileTable)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.FileTable)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_3.setObjectName("label_3")
        self.Button_FilePath = QtWidgets.QPushButton(self.FileTable)
        self.Button_FilePath.setGeometry(QtCore.QRect(240, 20, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        self.Button_FilePath.setFont(font)
        self.Button_FilePath.setObjectName("Button_FilePath")
        self.label_4 = QtWidgets.QLabel(self.FileTable)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(130, 285, 91, 31))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.FileButton = QtWidgets.QPushButton(self.FileTable)
        self.FileButton.setGeometry(QtCore.QRect(500, 210, 80, 23))
        self.FileButton.setObjectName("FileButton")
        self.MianButton = QtWidgets.QPushButton(self.FileTable)
        self.MianButton.setGeometry(QtCore.QRect(500, 180, 80, 23))
        self.MianButton.setObjectName("MianButton")
        self.ContextButton = QtWidgets.QPushButton(self.FileTable)
        self.ContextButton.setGeometry(QtCore.QRect(500, 240, 82, 23))
        self.ContextButton.setObjectName("ContextButton")
        self.FailButton = QtWidgets.QPushButton(self.FileTable)
        self.FailButton.setGeometry(QtCore.QRect(580, 0, 31, 23))
        self.FailButton.setObjectName("FailButton")
        self.splitter = QtWidgets.QSplitter(self.FileTable)
        self.splitter.setGeometry(QtCore.QRect(0, 300, 133, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.tabWidget.addTab(self.FileTable, "")
        self.ContentTable = QtWidgets.QWidget()
        self.ContentTable.setObjectName("ContentTable")
        self.tabWidget.addTab(self.ContentTable, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 637, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文档操作工具"))
        self.Edit_Path.setPlaceholderText(_translate("MainWindow", "DirPath"))
        self.label.setText(_translate("MainWindow", "文件夹所在路径"))
        self.label_2.setText(_translate("MainWindow", "源数据"))
        self.label_3.setText(_translate("MainWindow", "目标数据"))
        self.Button_FilePath.setToolTip(_translate("MainWindow", "请选择文件所在路径下任意一个文件以便我们能顺利找到它们"))
        self.Button_FilePath.setText(_translate("MainWindow", "浏览"))
        self.FileButton.setText(_translate("MainWindow", "文件名替换"))
        self.MianButton.setText(_translate("MainWindow", "全部替换"))
        self.ContextButton.setText(_translate("MainWindow", "文件内容替换"))
        self.FailButton.setText(_translate("MainWindow", "异常"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FileTable), _translate("MainWindow", "文件操作"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContentTable), _translate("MainWindow", "工具"))

